sonar.projectKey=Thurferr_todos
sonar.organization=thurferr

# Analisa todo o repositório
sonar.sources=.

# Ignora pastas que não devem ser analisadas
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/.git/**

# Cobertura de testes (quando existir)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificação
sonar.sourceEncoding=UTF-8
